Midna CLI builds working
NikitaVr/midna pull request #2
Opened 2023-10-03 15:14 UTC by NikitaVr

- changed a bunch of the dependencies to get built typescript working
- Building and running should work for all 3 now
  - Hardhat example deploy
  - Web app
  - Midna CLI

## Testing

Update all dependencies

```
yarn
```

### Run the web app

```
yarn web:dev
```

### Hardhat test

Update .env inside hardhat-example

```
MIDNA_URL=http://localhost:3000
MIDNA_API_URL=http://localhost:3000/api
```

start hardhate node

```
cd hardhat-example 
npx hardhat node
```

Deploy hardhat script (from new terminal)

```
cd hardhat-example 
npx hardhat run --network localhost scripts/deploy.ts
```

### CLI Test

Update .env inside midna-cli

```
MIDNA_URL=http://localhost:3000
MIDNA_API_URL=http://localhost:3000/api
```

Run CLI Command

```
cd midna-cli
./bin/run connect Counter 31337 0x34871293 0x53243 12312
```

## Screenshots
<img width="1443" alt="image" src="https://github.com/NikitaVr/midna/assets/10101970/2c85cd6c-7b1e-44c5-a972-6a938c80f30b">

2023-10-03 18:16 UTC, umar-ahmed requested changes
There's some references to your local filesystem still. Also, there are some unnecessary files and modules included

2023-10-03 18:16 UTC, umar-ahmed commented on hardhat-example/package.json
> +    "@midna/sdk": "/Users/nikita/Documents/chainpatrol/midna-sdk",
This won't work on other's machines

2023-10-03 18:16 UTC, umar-ahmed commented on hardhat-example/package.json
> +    "add": "^2.0.6",
where is this package used?

2023-10-03 18:16 UTC, umar-ahmed commented on hardhat-example/package.json
> +    "yarn": "^1.22.19"
yarn shouldn't be added as a dependency

2023-10-03 18:16 UTC, umar-ahmed commented on packages/db/.gitattributes
> +* text=auto
Why is this necessary?

2023-10-03 18:16 UTC, umar-ahmed commented on packages/rest/.gitignore
A lot of the stuff in this gitignore doesn't need to be repeated in each package. Just add to a root gitignore

2023-10-03 18:16 UTC, umar-ahmed commented on packages/rest/package.json
> +  "description": "Can log \"hello world\" and \"goodbye world\" to the console!",
?

2023-10-03 18:16 UTC, umar-ahmed commented on packages/rest/package.json
> -  "private": true,
Package should remain private

2023-10-03 18:16 UTC, umar-ahmed commented on web/data.db
should be gitignored

2023-10-03 18:16 UTC, umar-ahmed commented on packages/utils/package.json
> +    "tslib": "^2.6.2"
tslib seems unecessary, I think it's only used if `importHelpers` are enabled

2023-10-03 18:16 UTC, umar-ahmed commented on packages/sdk/src/index.ts
> +import { getCommitLink } from "./git.js";
why the file extension here?

2023-10-03 18:16 UTC, umar-ahmed commented on packages/db/package.json
> +    "@types/better-sqlite3": "^7.6.5",
dev dep

2023-10-03 18:16 UTC, umar-ahmed commented on packages/db/package.json
> +  "description": "Can log \"hello world\" and \"goodbye world\" to the console!",
?

2023-10-04 13:35 UTC, NikitaVr commented on packages/db/.gitattributes
> +* text=auto
some copy pasta, removing

2023-10-04 13:36 UTC, NikitaVr commented on packages/rest/.gitignore
good point, moved it up

2023-10-04 13:41 UTC, NikitaVr commented on packages/rest/package.json
> +  "description": "Can log \"hello world\" and \"goodbye world\" to the console!",
copy pasta, fixed

2023-10-04 14:13 UTC, NikitaVr commented on packages/db/package.json
> +  "description": "Can log \"hello world\" and \"goodbye world\" to the console!",
copy paste, cleaned up

2023-10-04 15:55 UTC, umar-ahmed requested changes
still see some things that should be removed

2023-10-04 15:55 UTC, umar-ahmed commented on .gitignore
> +yarn.lock
should not ignore lockfile, it's what determines the actual packages versions to pull in

2023-10-04 15:55 UTC, umar-ahmed commented on packages/db/package.json
> +    "tslib": "^2.6.2",
This should be removed from all packages

2023-10-04 15:55 UTC, umar-ahmed commented on packages/rest/package.json
> +    "zod": "^3.22.2"
zod can be listed as a peer dependency in all these packages. Many applications use it themselves, so describing it here might pull in duplicate versions

2023-10-04 20:59 UTC, umar-ahmed approved these changes
lgtm

2023-10-11 16:56 UTC, merged